# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        backendAzureRmSubscriptionId: 'd76415fd-d1f3-4359-8d5e-6121b38f3ad8'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'terraform-backend'
        backendAzureRmResourceGroupLocation: 'centralindia'
        backendAzureRmStorageAccountName: 'terraformbackenddotnet'
        backendAzureRmContainerName: 'terraform-backend-container'
        backendAzureRmKey: 'global/tfstate'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      inputs:
        command: 'output'
        allowTelemetryCollection: true