# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Azure for Students $(ARM_SUBSCRIPTION_ID)'
        backendAzureRmSubscriptionId: $(ARM_SUBSCRIPTION_ID)
        ensureBackend: false
        backendAzureRmResourceGroupName: $(TFStateBackendAzResourceGroup)
        backendAzureRmResourceGroupLocation: $(TFStateBackendAzRegion)
        backendAzureRmStorageAccountName: $(TFStateBackendAzStorageAcc)
        backendAzureRmContainerName: $(TFStateBackendAzStorageAccCont)
        backendAzureRmKey: $(TFStateBackendStorageAccContKey)
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      inputs:
        command: 'output'
        allowTelemetryCollection: true

    - bash: |
            echo ' $(TF_OUT_AZURE_CONTAINER_REGISTRY_ADMIN_PASSWORD)'
            echo ' $(TF_OUT_AZURE_CONTAINER_REGISTRY_ADMIN_USERNAME)'
            echo ' $(TF_OUT_AZURE_CONTAINER_REGISTRY)'
      displayName: echo tf output vars
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    

