# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'dockerregistrydotnet'
    #     repository: '3.net-microservices'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        azureContainerRegistry: '{"loginServer":"dockerregistrydotnet.azurecr.io", "id" : "/subscriptions/d76415fd-d1f3-4359-8d5e-6121b38f3ad8/resourceGroups/dockerdotnet/providers/Microsoft.ContainerRegistry/registries/dockerregistrydotnet"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services' 
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        azureContainerRegistry: '{"loginServer":"dockerregistrydotnet.azurecr.io", "id" : "/subscriptions/d76415fd-d1f3-4359-8d5e-6121b38f3ad8/resourceGroups/dockerdotnet/providers/Microsoft.ContainerRegistry/registries/dockerregistrydotnet"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        appName: 'dockerdotnetapp3net'
        multicontainerConfigFile: "./docker-compose.yml"
        # imageName: 'dockerregistrydotnet.azurecr.io/vaibhavhirani3netmicroservices_dotnetapp:latest'
        deployToSlotOrASE: true
        resourceGroupName: 'dockerdotnet'
        slotName: staging

    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        WebAppName: 'dockerdotnetapp3net'
        ResourceGroupName: 'dockerdotnet'
        SourceSlot: staging
        SwapWithProduction: true

