# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Builds the custom nginx image and pushes to private acr repo
    - task: Docker@2
      displayName: "Build & Push Custom Nginx Image"
      inputs:
        containerRegistry: 'dockerdotnet'
        repository: 'nginx'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile_Nginx'
        tags: 'latest'

    # Builds the docker compose file
    - task: DockerCompose@0
      displayName: "Builds docker compose file"
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        azureContainerRegistry: '{"loginServer":"dockerregistrydotnet.azurecr.io", "id" : "/subscriptions/d76415fd-d1f3-4359-8d5e-6121b38f3ad8/resourceGroups/dockerdotnet/providers/Microsoft.ContainerRegistry/registries/dockerregistrydotnet"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services' 
    
    # Pushes the image created from the docker compose file
    - task: DockerCompose@0
      displayName: "Pushes docker compose based image"
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        azureContainerRegistry: '{"loginServer":"dockerregistrydotnet.azurecr.io", "id" : "/subscriptions/d76415fd-d1f3-4359-8d5e-6121b38f3ad8/resourceGroups/dockerdotnet/providers/Microsoft.ContainerRegistry/registries/dockerregistrydotnet"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'

    # Deployment of the above created image to Staging Slot
    - task: AzureWebAppContainer@1
      displayName: "Deployment to Staging Slot"
      inputs:
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        appName: 'dockerdotnetapp3net'
        deployToSlotOrASE: true
        resourceGroupName: 'dockerdotnet'
        slotName: 'staging'
        multicontainerConfigFile: '**/docker-compose.yml'
    
    # Needs a task here, which can check the health of application deployed in Staging Slot and proceed accordingly to production deployment

    # Deployment of the above created image to Production Slot
    - task: AzureAppServiceManage@0
      displayName: "Swapping to Production Slot"
      inputs:
        azureSubscription: 'Azure for Students(d76415fd-d1f3-4359-8d5e-6121b38f3ad8)'
        WebAppName: 'dockerdotnetapp3net'
        ResourceGroupName: 'dockerdotnet'
        SourceSlot: staging
        SwapWithProduction: true
